/*
 * This file is part of αβspeedrun.
 * Copyright (C) 2025 Pigeonia Featurehouse
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.10-SNAPSHOT" apply false
    id 'org.cadixdev.licenser' version '0.6.1' apply false
    id "com.modrinth.minotaur" version "2.+" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

//def useNeoGradle = Boolean.valueOf(rootProject.use_neo_gradle)

subprojects { Project p ->
    //if (useNeoGradle && "neo" == p.name) return

    apply plugin: "dev.architectury.loom"
    //apply plugin: "io.github.juuxel.loom-vineflower"

    base {
        archivesName = rootProject.archives_base_name + '-' + project.name
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        // The following line declares the mojmap mappings, you may use other mappings as well
        //mappings loom.officialMojangMappings()
        //mappings loom.officialMojangMappings()
        // The following line declares the yarn mappings you may select this one as well.
        mappings "net.fabricmc:yarn:${rootProject.yarn_version}:v2"
    }
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'architectury-plugin'
    apply plugin: "maven-publish"
    apply plugin: 'org.cadixdev.licenser'

    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
        maven { url 'https://maven.neoforged.net/releases' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://mvn.7c7.icu' }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release.set 21
    }

    java {
        withSourcesJar()
    }

    license {
    	ignoreFailures = true
        include "**/*.java"
        include "./*.gradle"
        //skipExistingHeaders true
        charset 'utf-8'
        header rootProject.file('HEADER.txt')
        exclude '**/qj5/**/*.java'
    }
}

subprojects {
    if (!'common'.equals(project.name) && System.getenv("MR_TOKEN")) {
        apply plugin: 'com.modrinth.minotaur'
        def modLoaders = project.mr_loader.toString().split(",") as List
        modrinth {
            token.set System.getenv("MR_TOKEN")
            projectId.set rootProject.mr_project_id
            versionNumber.set "${project.version}-${modLoaders[0]}"
            versionName.set String.format(
                    /*format=*/rootProject.mr_version_name_format.toString(),
                    rootProject.mr_version_game_range,
                    project.mr_loader_display,
                    rootProject.mr_version_mod_abbr,
                    rootProject.mr_version_display
            )
            changelog.set rootProject.mr_version_changelog
            versionType.set rootProject.mr_version_type
            gameVersions = rootProject.mr_version_game.toString().split(",") as List
            loaders.set modLoaders
            detectLoaders.set false
            autoAddDependsOn.set false

            uploadFile.set tasks.remapJar
            additionalFiles = [tasks.remapSourcesJar]

            debugMode = System.getenv("MR_DEBUG_MODE") == '1'
        }
    }
}
